name: Refresh Long Beach Service Data

on:
  schedule:
    # Run 1 minute after 7am, 11am, 3pm, 7pm, 11pm, and 3am Pacific
    - cron: "1 14,18,22,2,6,10 * * *"
  workflow_dispatch:  # allows manual runs from GitHub interface

jobs:
  refresh:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full export
        run: python full_export.py

      - name: Run parser and summary
        run: python type_status_response_summary.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Auto update Long Beach service data ($(date -u))" || echo "No changes to commit"
          git push
