name: Automated Data Export and Summary

on:
  schedule:
    # Los Angeles times converted to UTC (LA is UTC−7 during Daylight Saving Time)
    - cron: "1 14 * * *"   # 7:01 AM LA (14:01 UTC)
    - cron: "1 18 * * *"   # 11:01 AM LA (18:01 UTC)
    - cron: "1 22 * * *"   # 3:01 PM LA (22:01 UTC)
    - cron: "1 2 * * *"    # 7:01 PM LA (02:01 UTC next day)
    - cron: "1 6 * * *"    # 11:01 PM LA (06:01 UTC next day)
    - cron: "1 10 * * *"   # 3:01 AM LA (10:01 UTC)
  workflow_dispatch:       # allow manual runs as well

jobs:
  export_and_parse:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # required to push changes back
      actions: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run exporter script
        run: |
          echo "Starting full data export..."
          python full_exporter.py

      - name: Run summary parser
        run: |
          echo "Running summary parser..."
          python type_status_response_summary.py

      - name: Duplicate latest summary file as current
        run: |
          echo "Copying latest summary file to summary_results_current.json..."
          latest_file=$(ls -t data/summary_stats_*.json | head -n 1)
          if [ -f "$latest_file" ]; then
            cp "$latest_file" data/summary_results_current.json
            echo "Copied $latest_file to summary_results_current.json"
          else
            echo "No summary_stats_*.json file found to copy."
          fi

      - name: Generate dashboards
        run: |
          echo "Generating dashboard HTML files..."
          python generate_dashboard.py

      - name: Commit and push updated data
        run: |
          echo "Checking for new or modified data files..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No new data changes detected. Skipping commit."
          else
            git commit -m "Automated dataset, summary, and dashboard update [skip ci]"
            git push
            echo "Changes pushed successfully."
          fi
